version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://www.uygunlik.uz/api
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=your_production_jwt_secret_here
      - CORS_ORIGIN=https://www.uygunlik.uz
    volumes:
      - ./client/uploads:/app/uploads
      - ./client/anor.db:/app/anor.db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./client/uploads:/var/www/uploads
    depends_on:
      - frontend
      - backend
    restart: unless-stopped



